Feniks/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
import settings
from marketing.sitemap import SITEMAPS
from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': SITEMAPS}),
    url(r'^', include('marketing.urls')),
    url(r'^', include('catalog.urls')),
]

admin.site.site_header = u'Администрирование - "Феникс"'

cart/urls.py
from django.conf.urls import url

from views import show_cart, confirm_order

urlpatterns = [
    url(r'^$', show_cart, {'template_name': 'cart/cart.html'}, 'show_cart'),
    url(r'^confirm/$', confirm_order, {}, 'confirm_order'),
]

search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from Feniks import settings
from catalog.models import Product


class SearchTerm(models.Model):
    q = models.CharField(u'Поисковая фраза', max_length=50)
    search_date = models.DateTimeField(u'Когда искали', auto_now_add=True)
    ip_address = models.GenericIPAddressField(u'IP-адрес')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, verbose_name=u'Пользователь')
    tracking_id = models.CharField(max_length=50, default='')

    class Meta:
        ordering = ['-search_date']
        verbose_name = u'Поисковый запрос'
        verbose_name_plural = u'Поисковые запросы'

    def __unicode__(self):
        return self.q


class Faq(models.Model):
    question = models.CharField(u'Вопрос', max_length=255, blank=True, unique=True)
    answer = models.TextField(u'Ответ', blank=True, unique=True)

    class Meta:
        verbose_name = u'Вопросы и ответы'
        verbose_name_plural = u'Вопросы и ответы'

    def __unicode__(self):
        return u'Вопрос №{}'.format(self.id)


class ActiveProductReviewManager(models.Manager):
    def all(self):
        return super(ActiveProductReviewManager, self).all().filter(is_approved=True)


class ProductReview(models.Model):
    RATINGS = ((5, 5), (4, 4), (3, 3), (2, 2), (1, 1),)
    product = models.ForeignKey(Product, verbose_name=u'Товар')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'Пользователь')
    date = models.DateTimeField(u'Создан', auto_now_add=True)
    rating = models.PositiveSmallIntegerField(u'Рейтинг', default=5, choices=RATINGS)
    is_approved = models.BooleanField(u'Одобрен', default=True)
    content = models.TextField(u'Текст')
    objects = models.Manager()
    approved = ActiveProductReviewManager()

    class Meta:
        verbose_name = u'Отзыв'
        verbose_name_plural = u'Отзывы'

templates/tags/cart_box.html
{% with cart_item_count as cart_count %}
    <a href="{% url 'show_cart' %}">
{#        <i class="fa fa-shopping-cart" aria-hidden="true"></i>#}
        <i class="fa fa-shopping-basket" aria-hidden="true"></i>
        Корзина ({{ cart_count }})
    </a>
{% endwith %}

templates/tags/category_list.html
<div id="MainMenu">
    <div class="list-group panel">
        <a href="#catgories" class="list-group-item cat_vertical collapse" data-toggle="collapse"
           data-parent="#MainMenu"><i class="fa fa-bars fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;КАТЕГОРИИ</a>

        <div class="collapse list-group-submenu" id="catgories">
            {% for cat in cats %}
                <a href="{{ cat.link }}" class="list-group-item cat_vertical">{{ cat.title }}</a>
            {% endfor %}
        </div>
    </div>

    <script>
        $('document').ready(function (e) {
            if ($(window).width() < 768) {
                $('div.panel').find('.collapse').collapse({toggle: false});
            } else {
                $('div.panel').find('.collapse').collapse({toggle: true});
            }
        });
    </script>
</div>

templates/tags/footer.html
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <a href="/about">&nbsp;О нас</a>
        </div>
        <div class="col-md-3">
            <a href="/contact">&nbsp;Контакты</a>
        </div>
        <div class="col-md-3">
            <a href="/delivery">&nbsp;Доставка</a>
        </div>
        <div class="col-md-3">
            <a href="/faq">&nbsp;Вопросы и ответы</a>
        </div>

        {#        {% with flatpage_list as pages %}#}
        {#            {% for page in pages %}#}
        {#                <div class="col-md-3">#}
        {#                    <a href="{{ page.url }}">{{ page.title }}</a>#}
        {#                </div>#}
        {#            {% endfor %}#}
        {#        {% endwith %}#}
    </div>
</div>

templates/tags/form_table_row.html
<tr>
    <th>
        {% if form_field.field.required %}*{% endif %}
        {{ form_field.label_tag }}
    </th>
    <td>
        {% if form_field.errors %}
            <ul class="errorlist">
                {% for error in form_field.errors %}
                    <li>{{ form_field.label }}: {{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {{ form_field }}
    </td>
</tr>

templates/tags/navigation.html
{#<ul>#}
{#    <li><a href="{% url 'catalog_home' %}">Главная</a></li>#}
{#    <li><a href="/about">О нас</a></li>#}
{#    <li><a href="/contact/">Контакты</a></li>#}
{#    <li><a href="/delivery/">Доставка</a></li>#}
{#</ul>#}
{#<div class="cb"></div>#}
{##}
{% load catalog_tags %}

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-left" href="{% url 'catalog_home' %}"><img alt="Brand" src="/static/images/logo_mini.png"></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/about"><i class="fa fa-users fa-lg" aria-hidden="true"></i>&nbsp;О нас</a>
                </li>
                <li>
                    <a href="/contact"><i class="fa fa-book fa-lg" aria-hidden="true"></i>&nbsp;Контакты</a>
                </li>
                <li>
                    <a href="/delivery"><i class="fa fa-truck fa-lg" aria-hidden="true"></i>&nbsp;Доставка и оплата</a>
                </li>
                <li>
                    <a href="/faq"><i class="fa fa-comments-o fa-lg" aria-hidden="true"></i>&nbsp;Вопросы и ответы</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'my_account' %}"><i class="fa fa-user fa-lg" aria-hidden="true"></i>&nbsp;{{ user.username }}</a>
                    </li>
                    <li>
                        <a href="{% url 'django.contrib.auth.views.logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Выйти</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'register' %}"><i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>&nbsp;Регистрация</a>
                    </li>
                    <li>
                        <a href="{% url 'django.contrib.auth.views.login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Войти</a>
                    </li>
                {% endif %}
                <li>
                    {% cart_box request %}
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/tags/pagination_links.html
{% if p.has_other_pages %}
    <nav aria-label="...">
        <ul class="pagination pagination-lg">
            {% if p.has_previous %}
                <li class="page-item">
                    <a class="page-link" aria-label="Previous"
                       href="{{ request.path }}?{{ params }}&page={{ p.previous_page_number }}">
                        &laquo; Предыдущая
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled" >
                    <a class="page-link">&laquo; Предыдущая</a>
                </li>
            {% endif %}
            <li class="page-item disabled"><a class="page-link"> Страница {{ p.number }} из {{ paginator.num_pages }} </a></li>
            {% if p.has_next %}
                <li class="page-item">
                    <a class="page-link" aria-label="Next" href="{{ request.path }}?{{ params }}&page={{ p.next_page_number }}">
                        Следующая &raquo;
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Следующая &raquo;</a>
                </li>
            {% endif %}

        </ul>
    </nav>
{% endif %}

templates/tags/product_list.html
{% for p in products %}
    {% if forloop.first %}
        <h3>{{ header_text }}</h3>
    {% endif %}
    {% include 'tags/product_thumbnail.html' %}
    {% if forloop.last %}
{#        <div >&nbsp;</div>#}
        <hr style="clear: both">
    {% endif %}
{% endfor %}

templates/tags/product_thumbnail.html
<div class="col-md-3 col-sm-4 col-xs-6 hero-feature">
    <div class="thumbnail">
        <a href="{{ p.get_absolute_url }}">
            {% if p.image %}
                {% if p.module_mebel == 'Шкаф' or p.module_mebel == 'Стул' or p.module_mebel == 'Кресло' %}
                    <img src="{{ p.image.url_180x200 }}" alt="{{ p.name }}" class="bn"/>
                {% else %}
                    <img src="{{ p.image.url_400x200 }}" alt="{{ p.name }}" class="bn"/>
                {% endif %}
            {% else %}
                <img src="http://placehold.it/300x200" alt="{{ p.name }}" class="bn"/>
            {% endif %}
            <div class="caption">
                <br/>
                {{ p.name }}
                <br>
                {{ p.price }} руб.
            </div>
        </a>
        {% if p.sale_price %}
            <div class="ribbon">
                <span class="sale">СКИДКА</span>
            </div>
        {% endif %}
        {% if p.new %}
            <div class="ribbon">
                <span class="new">НОВИНКА</span>
            </div>
        {% endif %}
        {% if p.is_bestseller %}
            <div class="ribbon">
                <span class="bestseller">ХИТ ПРОДАЖ</span>
            </div>
        {% endif %}
        {% if p.is_featured %}
            <div class="ribbon">
                <span class="featured">ВЫГОДНО</span>
            </div>
        {% endif %}
    </div>
</div>

templates/tags/search_box.html
<form role="form" class="form-group" id="search" action="{% url 'search_results' %}" method="get" style="margin-top: 20px">
    {#    <h3><label for="id_q">Поиск</label></h3>#}
    {{ form.q }}
    <button type="submit" class="btn">
        <i class="fa fa-search" aria-hidden="true"></i> Поиск
    </button>
</form>